project_id = "hqzizllylxkfwowwjwxe"

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-agent-webhook]
verify_jwt = false

[functions.wa-webhook]
verify_jwt = false

[functions.wa-agent]
verify_jwt = false

[functions.whatsapp-connect]
verify_jwt = false
